apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:  
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi  #Requesting 500MB of storage
  storageClassName: "standard" #This uses the standard storage class to provision the volume dynamically.



# To list the storage class: kubectl get storageclass