#Create a new service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-sa #Creatig a service account name custom-sa in the default namespace.
  namespace: default

---
#create a pod with the service account

apiVersion: v1
kind: Pod
metadata:
  name: service-account-pod  
spec:
  serviceAccountName: custom-sa #Adding the service account to the pod
  containers:
    - name: nginx-pod
      image: nginx

#Learnings
#A Service Account (SA) is an identity used by pods (or internal system processes) to interact with the Kubernetes API.
#Pods authenticate with kubernetes using the Token injected into pod.  Service Accounts let you securely control what a pod can do inside the cluster.
#By default every pod gets a default service account in its namespace.
#Kubernetes mounts a token in the pod at /var/run/secrets/kubernetes.io/serviceaccount/token inside the pod
#You can bind permissions using Role or ClusterRole.
#You should create a custom Service Account (SA) in Kubernetes whenever you want to give a specific pod or workload controlled access to the Kubernetes API. eg allow a pod to just list the resource and not delete

