apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
  nodeSelector:
    size: Large

#Learnings
#Assig labels to Nodes, Node selector uses this label to decide the node to schedule.
# It can be used to isolate pods or for compliance purpose, eg: to make sure it is deployed on a particular region nodes etc
#kubectl label node minikube size=Large. This will give the labe  to the node so that scheduling
