#Pod creation
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  containers:
  - name: mycontainer
    image: nginx
    ports:
    - name: http         # Giving name to port 80. It can be used later
      containerPort: 80

---
#Service creation

apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
  - port: 8080              # Service listens on 8080
    targetPort: http        # Sends traffic to containerPort named "http" (which is 80). Here we referred the namedport instead of IP.


#Learnings
#A named port is when you assign a custom name (string) to a container port — instead of just using a number. This name can then be used in Service definitions (especially useful when you have multiple ports).
#Its helpful when your container has many ports, and naming helps avoid confusion.
#You change port numbers often — you just change the name’s value in the Pod, not everywhere
