apiVersion: v1
kind: ConfigMap
metadata:
  name: env-app-config
data:
  APP_ENV: production
  APP_PORT: "8080"
  DB_HOST: mysql.db.internal

#Learnings
#Instead of mounting a ConfigMap as files, you can inject its key-value pairs directly into the container’s environment variables.
#This will add teh config map value as an environment variable inside the pod.
#Important: When config map is modified, the env will not automatically update instide the pod. You must restart/recreate the Pod to update the env.
