apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: host-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: host-volume
    hostPath:
      path: /data/nginx/html  #This is the directory in the host machine (Node).
      type: DirectoryOrCreate #It that directory do not exist, create it 

# What is hostPath?
# It mounts a directory or file from the host node’s filesystem directly into the Pod.
# Useful for: debugging, local data persistence, or accessing host-specific files.
# Be careful: hostPath ties your Pod to a specific Node, so it’s not portable.