apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-env
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password


#Learnings
#When you check the value of env variable "MY_PASSWORD", you can see the password printed

# You can load all keys at once:

# envFrom:
#   - secretRef:
#       name: my-secret


#Result
# root@pod-with-secret-env:/# echo $MY_PASSWORD
# abc123
# root@pod-with-secret-env:/# 

