apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-volume
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: my-secret-volume  #Reference the volume
          mountPath: "/etc/secret-data"  #Mount the volume to this path inside the pod
          readOnly: true
  volumes:
    - name: my-secret-volume  #Name of the volume to be created
      secret:
        secretName: my-secret #Use this secret. Secret is already created by secret.yaml


#Learnings
# When you log in to container and check the content of "/etc/secret-data". You can see a new file (password) is present that contain our password.

# root@my-first-pod:/etc/secret-data# cat password 
# abc123
# root@my-first-pod:/etc/secret-data# 