apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  password: YWJjMTIz   # base64 for abc123


#Learnings
#By default the secrets are not encrypted (But stored base64-encoded in etcd (no encryption).)
#In etcd, Secrets are only base64-encoded, not encrypted.
#Anyone with access to the Secret (via kubectl get secret ...) can decode it instantly:  echo 'YWRtaW4=' | base64 --decode
#The base64 encoding is only for YAML/JSON representation.
#This is purely a formatting step for transport between the API server and kubectl.
#To encode : echo "abc123" | base64

# Command to create a secret
# kubectl create secret generic my-secret --from-literal=password=abc123