apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJek1EZ3dNakF4TkRZek9Gb1hEVE16TURjek1UQXhORFl6T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWRJCjRnV3U1Wm1XWkZENEhXQjRBMzY2Y1FpOUFJVXNUV1JGZ3F1OTh4TzZDZXhDbWR4WFFIS1JTdFMyQ3RycXVQU2oKdUZpTzFMeXZ3ZnArMDBFTkNDYW1Cbll5Z2lKU1lKZGRnNnFyc3FUMWdvSTd2S2xTQzY1TWgwNDllUVkzVU9hMAowdUplNUp5OTFCTnpHZWhvYU5UZzNrT0lmRlpyUHBmOGQyUXFSWjRSN2RqcS82OVdjNnFPUVI1SVNLUnhUVWV6CmhSbGh1cEQxR3ZOd0Znc25hS3hWVkNPRmxQem5EVm50Qktzck0zcHoyTlB6cFVBQmdPakJQTGc0eWlOL0N3SGsKVytac0RTcFN3aCs2cDR3aGRIcmdwU3FVMUhkNXRndVBzRmdIUWpLREFpTktlRTVDazVIWWpiSlFJWG5OSVVFNgpvL2tndWpqZTh6RkFXY1VadUlzQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUbWRpVlpuM2lDMUJBZWRyWWpTdi9IaEVJMTJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFzUjFGRy9sSgpjd2MrUjFsT0pWTFRCNmNxdTBIQ21HSzk3c05iZDBSTkFJRDAzOGJqZnFqazl1MXg0bDM5UDB2amdkMzJRZ3JxCjU0UURZT1d0Sld3d3pxWW0zVGhKVE9wYzNzMDIzd1FZcGFUa3kvcWFXWldLRlM1ZUlJZlVPQTNDblhrQkxSeVEKampYSGdsQVRQTExGR2tSVVAwbG9saDFkY3dJRnArTFZ3VVdxL1NTVzFSUWRPajZFbXU1QzJxRTRFYWw4KzlkSgpvandyMWhQMHJtSU1aYXBLR3hVWHgrQlFjUjc4Rk0zbFcydWRkQTBhOGxiL2FUWVZpVVFJUEhvakRXdS9wVzUxCnZQLzFURjNwclkzaVJHMHNWVEY1cFB5OGJOWGN3TGsyekhZWFVsQUY1VTJMQXNYYW1kL0ljY0dNRGVreHF2dnYKMjE1ZHhGdDJtYmpHalE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://example.com:6443
  name: dev-cluster
contexts:
- context:
    cluster: dev-cluster
    namespace: dev-namespace
    user: dev-user
  name: dev-context
current-context: ""
kind: Config
preferences: {}
users:
- name: dev-user
  user:
    client-certificate-data: ZGVtbyBjZXJ0Cg==
    client-key-data: ZGVtbyBrZXkK
