apiVersion: v1
kind: Service
metadata:
  name: clusterip-service   #Name of the service
spec: 
  type: LoadBalancer #This will create an external load balancer infront of the nodes.
  selector:
    app: backend   #Service uses this selector to identify the backend pods that are to be added as endpoints.
  ports:
    - port: 8081  #Port where ther service listen to
      targetPort: 80 #Port where the service route the traffic to. ie, pods are listening to the mentioned port.


#Learnings
#Load balancer type creataes a loadbalancer infront of kubernetes cluster and receives the traffic from user and distribute it among the node(to the node port)
#Load balancer will also create a node port. the traffic from LB is forwarded to the nodePort IP
#Its just like placing a load balancer infront of the nodePort
#This works only when using managed Kubernetes services on cloud. It will not directly work even though you use EC2 kubeadm setup