apiVersion: v1
kind: ServiceAccount
metadata:
  name: list-pod-sa   #This is the name of the serice account
  namespace: default  #Service account will be created in the default namespace. SA are tied to namespaces


#Learning 
#This service account is used to list pods.
#Currently it dont perform any action because it is not binded to a role.
#Wken a role is binded to a service account, the SA will inherit the permission of the role.
#Check the role and role binding yaml