apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:  #It must match with the created PV for binding to work
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi  #Requesting 500MB of storage
  storageClassName: "" #This specifies to use the creatred PV and not to dynamically allocate a PV