apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:  #To specify a volume to mount
        - name: config-volume #use this volume to mount
          mountPath: /etc/config #mount the volume to this location inside the pod

  volumes:  #create a volume 
    - name: config-volume  #name of volume. this is referred by the pod to mount it
      configMap:
        name: my-config  #Name of config map to mount as volume

#Learnings
#A volume mount allows you to bring that ConfigMap into your Pod’s filesystem.
#Each key becomes a file, and the value is the content of that file.
#When both files are applied, the config map will be injected to the pod as a volume mount at /etc/config
#The key of the configmap will become a file, and value of config map will become the content of that file.
#when the config map is modified and reapplied, it will automatically update the file. No need to restart the pod
